### PR TITLE
added extra password checks and db connector

### PR DESCRIPTION
**Pull request by cyl-2**

### CODE REVIEW

**Comment by cyl-2** [comment]
still need to create a navbar for manager but these pages are working fine and emails can be sent to/from customers

**Comment by cyl-2** [comment]
When a new employee is added to the db by a manager, the password is randomly generated and will be sent to the employee's email account. The employee can then sign in with their email + password

**Comment by cyl-2** [comment]
@cahillBen For some reason, I can't login using email + password combination. Kinda freaking out. I can't figure out what the issue was. I changed all the db stuff to the mysqldb equivalent but still can't tell what the error is...the stuff has been inserted into the db properly soo :( 
can you check pweaseee

UPDATE 22/01 - I FIXED THE ISSUE

**Review by emmar266 — APPROVED** [review]
lgtm

**Pull request merged**
